-- Up
CREATE TABLE IF NOT EXISTS STORE_INFO (
                                        id           INTEGER PRIMARY KEY AUTOINCREMENT,
                                        OptCode         TEXT    NOT NULL,                 -- ROSTER.id
                                        info             TEXT    NOT NULL                 -- 'created' | 'updated' | 'deleted'
);


INSERT INTO STORE_INFO (OptCode, info) VALUES
     ('BKT', 'SHOP 1016, LEVEL 1, WESTPOINT SHOPPING CENTRE,<br>17 PATRICK STREET, BLACKTOWN, NSW 2148 <br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 Optometry<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone number: (02) 9621 8555<br>Medicare Online<br>Location ID: TOW01587<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 080355RF<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('BON', 'SHOP 1016, LEVEL 1, WESTFIELD BONDI,<br>500 OXFORD STREET,<br>BONDI JUNCTION, NSW 2022<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (02) 9389 1911<br>Medicare Online<br>Location ID: TOW01589<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 080355BX<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('BUR', 'SHOP 240, LEVEL 1, WESTFIELD BURWOOD,<br>100 BURWOOD ROAD,<br>BURWOOD, NSW 2134<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (02) 9744 0060<br>Medicare Online<br>Location ID: TOW01590<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 080355CH<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('CHC', 'SHOP B045, LG LEVEL, CHATSWOOD CHASE SHOPPING CENTRE,<br>345 VICTORIA AVENUE, CHATSWOOD, NSW 2067<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (02) 9413 2411<br>Medicare Online<br>Location ID: TOW01591<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 4124601X<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('HOB', 'SHOP 1026/7, LEVEL 1, WESTFIELD HORNSBY,<br>236 PACIFIC HIGHWAY,<br>HORNSBY, NSW 2077<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (02) 9987 2003<br>Medicare Online<br>Location ID: TOW01586<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 412460CX<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('PA1', 'SHOP 4036, LEVEL 4, WESTFIELD PARRAMATTA,<br>159 - 175 CHURCH STREET,<br>PARRAMATTA, NSW 2150<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (02) 9687 3100<br>Medicare Online<br>Location ID: TOW01599<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 0803556L<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('PEN', 'SHOP 62, LEVEL 1, WESTFIELD PENRITH,<br>585 HIGH STREET,<br>PENRITH, NSW 2750<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (02) 4761 0640<br>Medicare Online<br>Location ID: TOW01602<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 412460DH<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claming provider agreement form (HW027) available through Medicare Human Services.'),
     ('EAG', 'SHOP 245, LEVEL 1, WESTFIELD EASTGARDENS,<br>152 BUNNERONG ROAD,<br>EASTGARDENS, NSW 2036<br>Company registered name: AJ Eyecare Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 25 149 141 506<br>Account Name: AJ EYECARE<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 94-375-9979<br>Phone Number: (02) 9314 3331<br>Medicare Online<br>Location ID: TOW01594<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 4124608A<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('MQU', 'SHOP 34, LEVEL 1 - UPPER, MACQUARIE CENTRE,<br>CORNER HERRING & WATERLOO ROADS,<br>NORTH RYDE, NSW 2113<br>Registered Company Name: SK Eyecare Pty Ltd<br>Trading Name: 1001 Optical <br>Company A.B.N: 18 149 078 375<br>Account Name: SK EYECARE<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 94-375-7164<br>Phone Number: (02) 9889 8886<br>Medicare Online<br>Location ID: TOW01597<br>Payee Provider Name: Stephen Kwong<br>Payee Provider Number: 241645CY<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('TOP', 'SHOP LG2-1020, TOP RYDE CITY,<br>CORNER DEVLIN STREET & BLAXLAND ROAD,<br>RYDE, NSW 2112<br>Registered Company Name: JSJ Eyecare Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 22 159 280 716<br>Account Name: JSJ EYECARE<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 94-298-9748<br>Phone Number: (02) 9807 7711<br>Medicare Online<br>Location ID: TOW01585<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 4124603W<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('CHW', 'SHOP 257, LEVEL 1, WESTFIELD CHATSWOOD,<br>1 ANDERSON STREET, CHATSWOOD, NSW 2067<br>Registered Company Name: WSQ Eyecare Pty Ltd<br>Trading Name: 1001 Optical <br>Company A.B.N: 50 606 585 586<br>Account Name: WSQ EYECARE<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 77-126-2973<br>Phone Number: (02) 9411 1114<br>Medicare Online<br>Location ID: TOW01592<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 080355MJ<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('HUR', 'SHOP 151, WESTFIELD HURSTVILLE,<br>3 CROSS STREET AND PARK ROAD.<br>HURSTVILLE, NSW 2220<br>Registered Company Name: DJ Eyecare Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 36 668 354 461<br>Account Name: DJ EYECARE<br>Bank/Branch: National Australia Bank / Marrickville<br>BSB: 082-356<br>Account Number: 95-768-4226<br>Phone Number: (02) 9171 5638<br>Medicare Online<br>Location ID: TOW02212<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 412460FF<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('DON', 'SHOP 1113, LEVEL 1, WESTFIELD DONCASTER,<br>619 DONCASTER ROAD (CORNER WILLIAMSONS ROAD), DONCASTER, VIC 3108<br>Registered Company Name: CNC Eyecare Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 94 153 983 245<br>Account Name: CNC EYECARE<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 94-375-7316<br>Phone Number: (03) 9840 1001<br>Medicare Online<br>Location ID: TOW01593<br>Payee Provider Name: Alvin Lee<br>Payee Provider Number: 265165GJ<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('BOH', 'SP117, Box Hill Central Shopping Centre<br>1 MAIN STREET, BOX HILL, VIC 3128<br>Registered Company Name: CNC Eyecare Pty Ltd<br>Trading Name: 1001 Optical<br>Company A.B.N: 94 153 983 245<br>Account Name: CNC EYECARE<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 94-375-7316<br>Phone Number: (03) 9898 5456<br>Medicare Online<br>Location ID: TOW01588<br>Payee Provider Name: Alvin Lee<br>Payee Provider Number: 265165JH<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('EMP', 'Shop no. 3-034, Emporium Melbourne<br>287 Lonsdale St, Melbourne VIC 3000<br>Registered Company Name: 1001 Optical Pty Ltd<br>Trading Name: 1001 Optical<br>Company A.B.N: 78 145 835 383<br>Account Name: 1001 OPTICAL<br>Bank/Branch: National Australia Bank / Chatswood<br>BSB: 082-201<br>Account Number: 14-655-6116<br>Phone Number: (03) 9317 0011<br>Medicare Online<br>Location ID: TOW01611<br>Payee Provider Name: Christine Lee<br>Payee Provider Number: 412460EW<br>Medicare easyclaim:<br>We do not use Medicare easyclaim, we use medicare online through our POS (Optomate Touch).<br>Please complete the medicare online claiming provider agreement form (HW027) available through Medicare Human Services.'),
     ('IND', 'SHOP R01-016, INDOOROOPILLY SHOPPING CENTRE<br>322 MOGGILL RD, INDOOROOPILLY QLD 4068<br>Registered Company Name: 1001 Indooroopilly Pty Ltd<br>Trading Name: 1001 Optometry<br>Company A.B.N: 93 687 696 340<br>Account Name: 1001 Indooroopilly Pty Ltd<br>Bank/Branch: National Australia Bank / Marrickville<br>BSB: 082-356<br>Account Number: 92-166-7678<br>Phone Number: (07) 3378 0018<br>Medicare Online<br>Location ID: TOW02421<br>Payee Provider Name: Stephen Kwong<br>Payee Provider Number: 160091KX');



-- Down
DROP TABLE IF EXISTS STORE_INFO;